version: '3.4'

services:

  postgres:
    container_name: 'postgres'
    image: postgres
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: foodData

  catalog:
    container_name: 'catalog'
    image: ${DOCKER_REGISTRY-}catalog
    build:
      context: ../src/Food
      dockerfile: /Catalog/Dockerfile
    restart: unless-stopped
    ports:
      - 5001:80

  client:
    build:
      context: ../src/Food/Client
    image: ${DOCKER_REGISTRY-}client
    container_name: client
    command: npm run dev
    volumes:
    - .:/app
    - /app/node_modules
    ports:
      - "3000:3000"